.idea/webContexts.xml, pom.xml, src/main/java/com/projet/controller/LoginController.java, src/main/java/com/projet/controller/RegisterController.java, src/main/webapp/connected/index.jsp, src/main/webapp/connexion/index.jsp, src/main/webapp/form/index.jsp, src/main/webapp/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY4OGRlM2YxNDRmNTg1YWU0ZWNjYTIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.B6EqeRtq8tYPKyjrgiI8mhjM7ztnlLMU1R5JLy_rKm8">Huly&reg;: <b>PROJE-23</b></a></sub>
=> Refactor Register controller code and organize webapp directory

src/main/java/com/projet/controller/RegisterController.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzY5YzEzN2YxNDRmNTg1YWU0ZmQ2ZmIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.0xSjJgI8Ns19tF003PHUM_vRx5xD8fTjnMip-ntP76A">Huly&reg;: <b>PROJE-24</b></a></sub>
=> Refacor RegisterController for more readability

.idea/dataSources.xml, README.md, docker-compose.yml, src/main/resources/META-INF/persistence.xml, updateBDDInfoConnector.sh
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZhNzE0Y2YxNDRmNTg1YWU0ZmZlMmMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.khWUtVhnCp58IX2IyciTWC8Mv0DtrOHCqv8MTsORpNA">Huly&reg;: <b>PROJE-26</b></a></sub>
=> configure docker database and edit readme

src/main/java/com/projet/utils/button/Button.java, src/main/java/com/projet/utils/button/ButtonStrategy.java, src/main/java/com/projet/utils/button/Main.java, src/main/java/com/projet/utils/button/action/Heal.java, src/main/java/com/projet/utils/button/action/MoveDown.java, src/main/java/com/projet/utils/button/action/MoveLeft.java, src/main/java/com/projet/utils/button/action/MoveRight.java, src/main/java/com/projet/utils/button/action/MoveUp.java, src/main/java/com/projet/utils/button/action/productUnit.java
J'ai utilisé le design pattern strategy pour implementer les actions de deplacement de la grille.
La ce sont juste des exemples mais faudra modifer ce que pourra faire les bouttons en ce concertant
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZmZDY3ZmYxNDRmNTg1YWU1MTM2MDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.CsVK4FiA_z42ALDZ7C5Hn_y5sK1ROwnA_IjwI7K0Fbg">Huly&reg;: <b>PROJE-29</b></a></sub>
=> Implementation button action strategy pattern

.idea/misc.xml, src/main/java/com/projet/model/Foret.java, src/main/java/com/projet/model/Joueur.java, src/main/java/com/projet/model/Montagne.java, src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/model/Ville.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcwMTEwY2YxNDRmNTg1YWU1MTM4MDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.WzjDHuEBsq6fQ9p1lx9SS_LmqmIehTn3d5PanHVeYlU">Huly&reg;: <b>PROJE-30</b></a></sub>
=> correction/ajout methode foret + ville

src/main/java/com/projet/model/Foret.java, src/main/java/com/projet/model/Grille.java, src/main/java/com/projet/model/Joueur.java, src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/model/Ville.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcxNmYxYWYxNDRmNTg1YWU1MTQ4YjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.ocE7JeFrKde-rVjj2QJK2CrXrAKYdLIp-7IwztxooZM">Huly&reg;: <b>PROJE-37</b></a></sub>
=> ajout methode

src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/model/Ville.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzcyYWFmNmYxNDRmNTg1YWU1MTZjNGMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.S2usQkOZHVIatB_aitcxfLLsxN84JcXTr8GMqJXi0Is">Huly&reg;: <b>PROJE-40</b></a></sub>
=> ajout methode soldat

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/controller/CreateGrilleServlet.java, src/main/java/com/projet/utils/button/actionMove/MoveMethod.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1MzQ2YWYxNDRmNTg1YWU1MjAxMDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.jcNH-vtrGC42AzLsC1nIHi4cEsRFWbz-Wjl67kXtWq4">Huly&reg;: <b>PROJE-44</b></a></sub>
=> correct bug move en dehors grille

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/model/Tuile.java, src/main/java/com/projet/persistence/GrilleDAO.java, src/main/java/com/projet/persistence/SoldatDAO.java, src/main/java/com/projet/utils/button/actionMove/MoveMethod.java, src/main/resources/META-INF/persistence.temp.xml
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1NzUxNmYxNDRmNTg1YWU1MjA0ZDkiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.tlLMoJfvZg2OO1D9Ey0PiirOLQFhgyD4qSxDJDfbL1w">Huly&reg;: <b>PROJE-45</b></a></sub>
=> feature move soldat

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/model/Joueur.java, src/main/java/com/projet/persistence/GrilleDAO.java, src/main/java/com/projet/persistence/JoueurDAO.java, src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1ODE4N2YxNDRmNTg1YWU1MjA2YzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.SRU3vE04DL67kCgWPdDfDT1-nH6X5RsqiiEMxPH3H2E">Huly&reg;: <b>PROJE-46</b></a></sub>
=> correct beug generer grille et correct propriétaire

pom.xml, src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/model/TypeTuile.java, src/main/java/com/projet/utils/button/actionMove/MoveMethod.java, src/main/java/com/projet/utils/other/Database/Main.java, src/main/java/com/projet/utils/other/Database/PoolSizeChecker.java, src/main/java/com/projet/utils/other/Database/TableResetUtil.java, src/main/resources/META-INF/persistence.temp.xml
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Nzc1YmY0ZGYxNDRmNTg1YWU1MjBkNTEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.N84iYh2CKHHjG26osVwnWB1_FPFLkWtau3gbcOVs0DY">Huly&reg;: <b>PROJE-52</b></a></sub>
=> problème de pool regler

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/model/Soldat.java, src/main/java/com/projet/persistence/DAOFactory.java, src/main/java/com/projet/persistence/TuileDAO.java, src/main/java/com/projet/utils/button/actionMove/MoveDown.java, src/main/java/com/projet/utils/button/actionMove/MoveLeft.java, src/main/java/com/projet/utils/button/actionMove/MoveMethod.java, src/main/java/com/projet/utils/button/actionMove/MoveRight.java, src/main/java/com/projet/utils/button/actionMove/MoveUp.java, src/main/java/com/projet/utils/other/Database/Main.java, src/main/resources/META-INF/persistence.temp.xml
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdhOTgyZmYxNDRmNTg1YWU1MjkxN2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.EAcoPh1TEmYI5AdWqK2zJdyt7WUh_bD0vfTePhk0EyA">Huly&reg;: <b>PROJE-57</b></a></sub>
=> regler souci deplacement

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/persistence/DAOFactory.java, src/main/java/com/projet/persistence/ForetDAO.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdhOWRlYWYxNDRmNTg1YWU1MjkyM2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.x5oOINjdVNJ8F5JIsWnJBHqg8TPDlJcdjheKuOC5gLg">Huly&reg;: <b>PROJE-58</b></a></sub>
=> refactoriser foret et correction

src/main/java/com/projet/controller/GameSessionServlet.java, src/main/webapp/css/grille.css, src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdhYWY2YWYxNDRmNTg1YWU1Mjk1M2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.e2Dr2QFxqG1tgtoG-QqEwcXKfojlJjCjR9y49r8tA-Y">Huly&reg;: <b>PROJE-59</b></a></sub>
=> modification grille css

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/controller/FrontControllerServlet.java, src/main/java/com/projet/model/Soldat.java, src/main/resources/META-INF/persistence.temp.xml, src/main/webapp/css/grille.css, src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdjMmIwNWYxNDRmNTg1YWU1MmU3MDQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.EObT4RopP3830VOHr7UxRxiMz-gz0TxoE6HulFvamhM">Huly&reg;: <b>PROJE-62</b></a></sub>
=> ajout feature foret et guerir fix css

src/main/java/com/projet/model/Grille.java
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlOWY4OGYxNDRmNTg1YWU1MzQ1MTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.mqu09oyx1I0X5nUIwuGfeCKZudY-lWWzDJNoCLvmnUM">Huly&reg;: <b>PROJE-65</b></a></sub>
=> Fix feature updateScore

src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzdlZTY0M2YxNDRmNTg1YWU1MzRlZDIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.zg0BujpyvM9fwbHHvaepZGQpM1uUBIevz8nGq4mrKfM">Huly&reg;: <b>PROJE-68</b></a></sub>
=> ajout d'un bouton rejoindre une autre partie

src/main/java/com/projet/controller/ActionsController.java, src/main/java/com/projet/controller/RegisterController.java, src/main/java/com/projet/model/Grille.java, src/main/java/com/projet/model/Joueur.java, src/main/java/com/projet/model/Ville.java, src/main/java/com/projet/persistence/VilleDAO.java, src/main/resources/META-INF/persistence.temp.xml, src/main/webapp/css/grille.css, src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgxMjkyM2JjMjA5NGNjMDE4MzFhMjciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.lqvUNi2b3ZEW2pcQ8eycXcET4lozqZvTsnnhVE9MszE">Huly&reg;: <b>PROJE-69</b></a></sub>
=> ajout liste ville dans grille

src/main/webapp/connected/index.jsp, src/main/webapp/connexion/index.jsp, src/main/webapp/css/grille.css, src/main/webapp/css/home.css, src/main/webapp/css/login.css, src/main/webapp/css/menuConnexion.css, src/main/webapp/css/parties.css, src/main/webapp/css/register.css, src/main/webapp/form/index.jsp, src/main/webapp/grille/index.jsp, src/main/webapp/index.jsp, src/main/webapp/parties/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgxNGM5NmJjMjA5NGNjMDE4M2IyYTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.GR97GnLN-yP0nZ_C1kknItVXSMXoA6dOxu686VJXL1U">Huly&reg;: <b>PROJE-70</b></a></sub>
=> Création des fichier css

src/main/webapp/css/grille.css, src/main/webapp/grille/index.jsp
<sub><a href="https://huly.app/guest/test-670b88d0-0eabc1aa9c-4fe603?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzgxNTg4MmJjMjA5NGNjMDE4NDAyYTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViaGFkanVzLXRlc3QtNjcwYjg4ZDAtMGVhYmMxYWE5Yy00ZmU2MDIifQ.wCniHueUzfP0G-bBPvZcoQsSDjbPJKwrIPEax7z4mBI">Huly&reg;: <b>PROJE-71</b></a></sub>
=> Fix bug css
